### ISSUE TITLE
Unable to use pakler after install

### ISSUE THREAD

**Issue by toba321** [vmallet/pakler#2]
Hi,
I'm sure it's just something silly I'm doing but after installing pakler I am unable to use it. 
To install I use the command` pip install pakler`
I then import the module and no commands work for instance `pakler -h` returns that h is not defined. 

![image](https://user-images.githubusercontent.com/75487499/215583220-de66d16a-1f86-44e5-9097-329155206ca4.png)

Any help would be much appreciated. 

Thank you

**Comment by vmallet** [comment]
@Chief-T1, have you tried running it straight from the command line? Right now I see you launched the python interpreter, and tried to invoke `pakler` from there. It gets confused because `pakler -h` is a bash command, not a python command.

Try returning to the shell (where you ran `pip install pakler`) and running `pakler -h` from there, it should work then.

**Comment by toba321** [comment]
Thanks for the help, that was exactly it. I knew it was something silly I was doing. 

I've now successfully extracted the pak file which gives the following files.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/75487499/217358526-5248a78d-41cb-493f-ba62-d629be594969.png">

But I am unsure how to proceed from here if I want to view the individual files within the pak firmware. 
I've done a bit of reading and have installed binwalk. 

I ran the command ` binwalk -e 07_app.bin` which outputs a single file called `0.ubi`
<img width="384" alt="image" src="https://user-images.githubusercontent.com/75487499/217359986-1c232ea7-c1de-4fb9-82ed-3d358aef0ad6.png">

I understand this is another file system and I'm not sure how to expand this. Sorry this is very new to me and I don't want to waste too much of your time if there is a lot more knowledge involved but if I'm nearly there in terms of the commands I would appreciate it if you can please point me in the right direction. 

Thank you

**Comment by AT0myks** [comment]
In this case the `app` section is a UBI file system. Install [ubi_reader](https://github.com/jrspruitt/ubi_reader) and then run `ubireader_extract_files 07_app.bin`.

**Comment by vmallet** [comment]
Hope you got what you needed out of these files @Chief-T1. Closing this issue as I believe this is not on Pakler.
